export const FETCH_PRODUCTS_INIT = 'FETCH_PRODUCTS_INIT';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCT_ITEM_INIT = 'FETCH_PRODUCT_ITEM_INIT';
export const FETCH_PRODUCT_ITEM_SUCCESS = 'FETCH_PRODUCT_ITEM_SUCCESS';
export const FETCH_PRODUCT_ITEM_FAILURE = 'FETCH_PRODUCT_ITEM_FAILURE';